editor: source

execute:
  cache: false # "Danger, Will Robinson!"
  freeze: false # If you plan to use it, remember to disable it afterward!

# quarto render --profile html

profile:
  group:
    - [gfm, html]
  default: gfm
